### PR TITLE
adds tagline & twitter

### PR DESCRIPTION
**Pull request by hxrts**
nothing fancy, just including the basics!!!!!!!!!!!!!!!!!!!!!!!!!

### CODE REVIEW

**Comment by louiscenter** [comment]
@clevinson seems to be a build error:

```
./build_cv.sh: No such file or directory
```

Any ideas?

**Comment by clevinson** [comment]
@hxrts strange to me that github isn't showing this in the UI... but it looks like ur version of master isn't up to date wit the most recent commits from my last PR (which included the `./build_cv.sh` file).

Can you rebase from `guild-is:master` and see if tests pass then ?

**Comment by keikreutler** [comment]
@hxrts i just realized i can edit other people's comments on github ✌️

**Comment by hxrts** [comment]
With great admin privileges, comes great responsibility.

**Pull request merged**
